version: 2
jobs:
  build:
    machine: true
    #branches:
      #only:
      #  - master
    steps:
      - run:
          name: Install required tools
          command: pip install prettytable
      - checkout
      - run:
          name: Pull test images (if possible)
          command: ./tests/integration/test.py pull || true
      - run:
          name: Run integration tests
          command: ./tests/integration/test.py run
